#!/usr/bin/env python

from gi.repository import Gtk

class gBsdConv(object):       
	def __init__(self):
		builder = Gtk.Builder()
		builder.add_from_file("gbsdconv.xml")
		self.window = builder.get_object("main_window")
		self.window.connect('destroy', Gtk.main_quit)

		zh_maps_list = builder.get_object("zh_maps_list")
		zh_maps_list.append_text('None')
		zh_maps_list.set_active(0)

		self.window.show()

if __name__ == "__main__":
	app = gBsdConv()
	Gtk.main()
